## TODO: make some tests!
## - markupUnmarked.py testing

language: python
python:
  - "3.5" # server version
  - "3.8" # devs' version
env: 
  - DJANGO=2.2.12 TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata
before_install:
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr
  - sudo apt-get install tesseract-ocr-rus
  - sudo find / -name "tessdata"
install:
  - pip install -r requirements.txt
#  - pip install flake8
# Disable linter since there is no time for fixing its mistakes
# before_script:
#  - "flake8 ."
script:
  - python manage-memesearch.py test tests.test_model

